### ISSUE TITLE
Support for Zeebe Multi-instance SubProcess Loop 

### ISSUE THREAD

**Issue by vtexier** [germaniumhq/adhesive#2]
I am working on adhesive to add the support of BPMN workflows created by the [BPMN Zeebe Modeler](https://github.com/zeebe-io/zeebe-modeler).

I am stuck trying to setup variable mapping in the Multi-instance SubProcess Loop.

Zeebe allow to configure a multi-instance subprocess, with this parameters:

|||
|-|-|
**InputCollection** | = variable_to_iterate
**InputELement**| variable_to_set
**OutputCollection** | variable_to_append_to
**OutputElement** | = variable_to_get

The loop will iterate the `InputCollection` list, and set the `InputElement` variable value to the current loop item from `InputCollection`.

The `subprocess` can then access the variable name set in the `InputElement`in his scope (adhesive context).

At the end of each `subprocess` execution, the `OutputElement` variable value is appended to the `OutputCollection` variable list.

At the end of the `subprocess` loop, the parent process get the `OutputCollection` variable name in his scope (adhesive context).

Where can I find in the code:
* Subprocess loop init (I think it is in `adhesive.model.loop_controller.create_collection_loop`, I already use it for the multi-instance task loop support)
* Subprocess start in each loop iteration  ?
* Subprocess end in each loop iteration  ?

Thanks for any help.

**Comment by bmustiata** [comment]
There is no variable mapping supported in _adhesive_, in the sense of rewriting variables as other names. Instead, the data is available on the token as `token.data` and is copied to the tasks. Loop information is in `token.loop` if you're inside a loop of any sort. This is intentional on the side of Adhesive.

Since for loops, the iterated data is available in the token, the actual values are available as `token.loop.value` (and `token.loop.key` if iterating over a dict). If you have iterables they are automatically expanded into execution tokens with the individual values. You don't need to manually remap them to new variables, just read them from the `token.loop.value`. If it's not an iterable you want to go over, i.e. you need to do something until an expression becomes `false` adhesive can do that as well. It will run the subprocess / task if the expression evaluates to `True`, then check again the expression. If it's again `True` is ran again. If you have a nested loop, the parent loop is available as well with `token.loop.parent`.

Here are a bunch of sample loop processes used in the integration tests: https://github.com/germaniumhq/adhesive/tree/master/features/processes/loop

Some of them are using the programmatic API where I'm constructing the BPMN process with some functions instead of reading it from a BPMN file, but behind the scenes, there's still the same BPMN graph evaluation and execution.

**Comment by vtexier** [comment]
Thanks for your answer!

I know that my project to add Zeebe XML support to Adhesive is overkill for the main purpose of building software, but I think Adhesive is a great BPMN engine and I wish I could use it to deal with other tasks. Zeebe has good ideas, the modeler is great, but the workflow engine is distributed and too heavy to use for my tasks.

> You don't need to manually remap them to new variables, just read them from the `token.loop.value`

Yes I need to. I want the task code to be loop agnostic.

The Zeebe approach has the advantage to not have to code which data a loop is dealing with. The mapping parameters of the loops are here for that. So loops can deal with any data at any step in the workflow, and task can be use by any loop without the task to be aware of it.

So, in my use case, when I write a task code, it is always using the same input variables and will put the results in the same output variables. When I use this task in a workflow with a loop, I inform the workflow engine (easily with Zeebe loop mapping parameters in the modeler) that a mapping is needed to populate the input variables of the task from the loop data (taken from any collection variable in the context), and to extract the loop results from the output data of the task, then put it in a new collection variable in the context.

I have already added the Zeebe parallel multi-instance loop mapping parameters support in Adhesive. Works fine.

I need to get an entry point in the subprocess parallel multi-instance loop code to apply the Zeebe mapping on subprocess as well.

**Comment by vtexier** [comment]
I managed to achieve the Zeebe Multi-instance SubProcess Loop support.

I have added a local variable scope to tasks to avoid variable name collision in context.data.

No more question for now.
